name: GoogleAdMobMonitor

options:
  bundleIdPrefix: com.jamesbaker
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    majorVersion: 8.0.0

targets:
  GoogleAdMobMonitor:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - GoogleAdMobMonitor
    scheme:
      gatherCoverageData: false
    info:
      path: Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.974734396380-uoj0bbfdj2r7prlu5p1nim3h3dq53vhq
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jamesbaker.googleAdMobMonitor
        INFOPLIST_KEY_CFBundleDisplayName: "AdMob Stats"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    resources:
      - GoogleAdMobMonitor/Assets.xcassets
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
